### ISSUE TITLE
Web components integration into the new Forms Library

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#74]
## Task Description
What does it take to integrate Design System web components into a form using the new Forms Library?

### Why this?
Being able to easily use web components within the Forms Library would provide a wider range of functionality to support use cases above and beyond basic, plain vanilla forms.

## Acceptance Criteria
- [ ] Research has been synthesized into a Confluence document in the FLT workspace
- [ ] That Confluence document includes a summary of the investigation activities, degree of ease or difficulty to integrate Design System web components into a form using the new Forms Library, and suggestions for improving how this works (if applicable).

**Comment by bkjohnson** [comment]
For some technical context, the form builder portion of `formulate` is already making use of web components from the design system. Each "field" imports a react binding for the web component (this makes it easier to assign event handlers). 

Here's an example of that import:

https://github.com/department-of-veterans-affairs/formulate/blob/8e6e4efbcdfcbdd9d8a501c401ec97b1196dd2c2/src/form-builder/TextField.tsx#L6

The formulate field is basically a light wrapper over our web components in order to get them hooked up into Formik's global form state.

**Comment by taylorkaren** [comment]
12/17 standup: @micahchiang will add a link to documentation about how this works, then close this ticket.

**Comment by micahchiang** [comment]
The new forms library already uses web components as the core building blocks for each individual form field. [The text input](https://github.com/department-of-veterans-affairs/formulate/blob/master/src/form-builder/TextField.tsx#L6) is a prime of example of this, as the react bindings for the va-text-input] are imported and used. From there, forms that are composed with the new forms library import Formik and use that as a [wrapper around specified fields](https://department-of-veterans-affairs.github.io/formulate/tutorials/getting-started.html)
